version: "3"

services:
  node-0:
    image: redis:latest
    container_name: redis-node-7000
    ports:
      - "7000:7000"
      - "17000:17000"
    command: >
      redis-server --port 7000 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7000 
      --cluster-announce-bus-port 17000
    volumes:
      - ./data/7000:/data

  node-1:
    image: redis:latest
    container_name: redis-node-7001
    ports:
      - "7001:7001"
      - "17001:17001"
    command: >
      redis-server --port 7001 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7001 
      --cluster-announce-bus-port 17001
    volumes:
      - ./data/7001:/data

  node-2:
    image: redis:latest
    container_name: redis-node-7002
    ports:
      - "7002:7002"
      - "17002:17002"
    command: >
      redis-server --port 7002 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7002 
      --cluster-announce-bus-port 17002
    volumes:
      - ./data/7002:/data

  node-3:
    image: redis:latest
    container_name: redis-node-7003
    ports:
      - "7003:7003"
      - "17003:17003"
    command: >
      redis-server --port 7003 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7003 
      --cluster-announce-bus-port 17003
    volumes:
      - ./data/7003:/data

  node-4:
    image: redis:latest
    container_name: redis-node-7004
    ports:
      - "7004:7004"
      - "17004:17004"
    command: >
      redis-server --port 7004 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7004 
      --cluster-announce-bus-port 17004
    volumes:
      - ./data/7004:/data

  node-5:
    image: redis:latest
    container_name: redis-node-7005
    ports:
      - "7005:7005"
      - "17005:17005"
    command: >
      redis-server --port 7005 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes 
      --cluster-announce-ip 127.0.0.1 
      --cluster-announce-port 7005 
      --cluster-announce-bus-port 17005
    volumes:
      - ./data/7005:/data
